### ISSUE TITLE
timeout is not working. Also looking at the C specs, it doesn't look like there is a timeout setting for connection or response, only on FTP connect.

### ISSUE THREAD

**Issue by slalli** [shabiel/fis-gtm-plugins#2]
It returned, after 10 seconds, ,%YDB-E-ZCSTATUSRET, External call returned error status

**Comment by shabiel** [comment]
I use this: https://curl.se/libcurl/c/CURLOPT_TIMEOUT.html

It's timeout in seconds.

**Comment by slalli** [comment]
> I use this: https://curl.se/libcurl/c/CURLOPT_TIMEOUT.html
> 
> It's timeout in seconds.

Indeed, I was looking at CURLOPT_ACCEPTTIMEOUT_MS

Still, CURLOPT_TIMEOUT is the timeout of the entire operation, which  don't "think" it is the right one. (but I am maybe wrong)

That's why it was not working when I shut down a machine, this counter start to count only AFTER CONNECTION.... 
Call comes back after 10 seconds and M error is triggered...

We should use the following (correct me if I am wrong):
[CURLOPT_CONNECTTIMEOUT_MS](https://curl.se/libcurl/c/CURLOPT_CONNECTTIMEOUT_MS.html)
for connection timeout (the most important, now it is set to 10 seconds)

and

CURLOPT_SERVER_RESPONSE_TIMEOUT_MS
for response timeout, in case the we connect but the server crashes or hang...

And in milliseconds....

Maybe we can change this when we port the code to YottaDB Plugin...

In my request I already have:
        timeouts: {
            onConnect: 3000,
            onResponse: 500,
        }

but I am ignoring them for the moment...

**Comment by shabiel** [comment]
Implemented in 2b55404.
